// <auto-generated />
using System;
using EquipmentDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EquipmentDatabase.Migrations
{
    [DbContext(typeof(EquipmentContext))]
    [Migration("20200617191959_Database")]
    partial class Database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EquipmentDatabase.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("EquipmentDatabase.Properties", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defence")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<int>("Inteligence")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("UniqueId")
                        .HasColumnType("int");

                    b.Property<int?>("UniqueItemUniqueId")
                        .HasColumnType("int");

                    b.HasKey("PropertyId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UniqueItemUniqueId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("EquipmentDatabase.Rareties", b =>
                {
                    b.Property<int>("RaretyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int");

                    b.Property<string>("Rarety")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniqueId")
                        .HasColumnType("int");

                    b.Property<int?>("UniqueItemUniqueId")
                        .HasColumnType("int");

                    b.HasKey("RaretyId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UniqueItemUniqueId");

                    b.ToTable("Rarety");
                });

            modelBuilder.Entity("EquipmentDatabase.Types", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniqueId")
                        .HasColumnType("int");

                    b.Property<int?>("UniqueItemUniqueId")
                        .HasColumnType("int");

                    b.HasKey("TypeId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UniqueItemUniqueId");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("EquipmentDatabase.UniqueItem", b =>
                {
                    b.Property<int>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UniqueItemName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueId");

                    b.ToTable("UniqueItems");
                });

            modelBuilder.Entity("EquipmentDatabase.Properties", b =>
                {
                    b.HasOne("EquipmentDatabase.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipmentDatabase.UniqueItem", "UniqueItem")
                        .WithMany()
                        .HasForeignKey("UniqueItemUniqueId");
                });

            modelBuilder.Entity("EquipmentDatabase.Rareties", b =>
                {
                    b.HasOne("EquipmentDatabase.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipmentDatabase.UniqueItem", "UniqueItem")
                        .WithMany()
                        .HasForeignKey("UniqueItemUniqueId");
                });

            modelBuilder.Entity("EquipmentDatabase.Types", b =>
                {
                    b.HasOne("EquipmentDatabase.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipmentDatabase.UniqueItem", "UniqueItem")
                        .WithMany()
                        .HasForeignKey("UniqueItemUniqueId");
                });
#pragma warning restore 612, 618
        }
    }
}
